- name: Update repo
  apt:
    update_cache: yes    

- name: Upgrade all system packages
  apt:
    upgrade: dist

- name: Remove dependencies that are no longer required
  apt:
      autoremove: yes
